export const UPDATE_SPECIES_SELECTED = 'UPDATE_SPECIES_SELECTED';
export const UPDATE_LOCATION_SELECTED = 'UPDATE_LOCATION_SELECTED';
export const UPDATE_USER_COORDINATES = 'UPDATE_USER_COORDINATES';
