export const UPDATE_SPECIES_SELECTED = 'UPDATE_SPECIES_SELECTED';
export const UPDATE_LOCATION_SELECTED = 'UPDATE_LOCATION_SELECTED';
export const UPDATE_USER_COORDINATES = 'UPDATE_USER_COORDINATES';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const UPDATE_PAGE_NUMBER = 'UPDATE_PAGE_NUMBER';
